<a href="https://colab.research.google.com/github/coldsober-irene/hackathon1/blob/main/intelligent_translator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pyngrok uvicorn nest-asyncio fastapi easynmt

In [2]:
!ngrok authtoken 2HJPvK5e4VxcduBjO5XSc0LqqCR_5zV3b5gBcKuNMUnxdpfuP

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml

In [72]:
from pyngrok import ngrok
from fastapi import FastAPI, Response
import uvicorn
import nest_asyncio 
from starlette.responses import HTMLResponse
import json
import pandas as pd
import numpy as np
from string import ascii_uppercase
from easynmt import EasyNMT

In [95]:
col = [i for i in str(ascii_uppercase)][:3]
sentences = [["I want to know where things are stucking",
              "i don't know what i can do",
              "this is the final sentence"],
              ['this sentence is number two',
               'and i need the box',
               'a box with the box it is'],
             ["column is just nothing",
              "the last ship was amazing",
              "what a beautiful day"],
             ["this is the last hour",
              "the very tough coding challenge",
              "wonderful and hard to manage"]]
# data = pd.DataFrame(np.array(np.arange(100)).reshape(5,-1), columns = col)
data = pd.DataFrame(sentences, columns = col)

In [96]:
model = EasyNMT('opus-mt')
app = FastAPI(title = 'ME')
prev = 'en'
@app.get('/let')
def do(lang:str=''):
  global prev
  for index in range(len(data)):
    data['A'][index] = model.translate(data.iloc[index]['A'], source_lang = prev, target_lang = lang)
    data['B'][index] = model.translate(data.iloc[index]['B'], source_lang = prev, target_lang = lang)
    prev = str(lang)
  return Response(data.to_json(orient = 'values'), media_type = 'application/json')

In [97]:
tunnel = ngrok.connect(8000)
print(tunnel.public_url)
nest_asyncio.apply()
uvicorn.run(app, port = 8000)

INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [73]

In [94]:
data.head()

,A,B,C
0,Me gustaría saber por qué las cosas no habían ...,"No sé qué hacer.""",this is the final sentence
1,this sentence is number two,and i need the box,a box with the box it is
2,column is just nothing,the last ship was amazing,what a beautiful day
3,this is the last hour,the very tough coding challenge,wonderful and hard to manage

In [55]:
for index in range(len(data)):
  z = data.iloc[index]['T'] ** 3
  print(z)
  data['T'][index] = data.iloc[index]['T'] ** 3

6859
59319
205379
493039
970299

In [56]:
data.head()

,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T
0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,6859
1,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,59319
2,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,205379
3,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,493039
4,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,970299

In [4]:
app = FastAPI(title = 'MY API')
@app.get('/')
def start():
  return "this is the beginning of the page"

In [11]:
langs = '''{"Abkhaz": "ab",
 "Afar": "aa",
 "Afrikaans": "af",
 "Akan": "ak",
 "Albanian": "sq",
 "Amharic": "am",
 "Arabic": "ar",
 "Aragonese": "an",
 "Armenian": "hy",
 "Assamese": "as",
 "Avaric": "av",
 "Avestan": "ae",
 "Aymara": "ay",
 "Azerbaijani": "az",
 "Bambara": "bm",
 "Bashkir": "ba",
 "Basque": "eu",
 "Belarusian": "be",
 "Bengali": "bn",
 "Bihari": "bh",
 "Bislama": "bi",
 "Bosnian": "bs",
 "Breton": "br",
 "Bulgarian": "bg",
 "Burmese": "my",
 "Catalan; Valencian": "ca",
 "Chamorro": "ch",
 "Chechen": "ce",
 "Chichewa; Chewa; Nyanja": "ny",
 "Chinese": "zh",
 "Chuvash": "cv",
 "Cornish": "kw",
 "Corsican": "co",
 "Cree": "cr",
 "Croatian": "hr",
 "Czech": "cs",
 "Danish": "da",
 "Divehi; Dhivehi; Maldivian;": "dv",
 "Dutch": "nl",
 "English": "en",
 "Esperanto": "eo",
 "Estonian": "et",
 "Ewe": "ee",
 "Faroese": "fo",
 "Fijian": "fj",
 "Finnish": "fi",
 "French": "fr",
 "Fula; Fulah; Pulaar; Pular": "ff",
 "Galician": "gl",
 "Georgian": "ka",
 "German": "de",
 "Greek, Modern": "el",
 "Guaraní": "gn",
 "Gujarati": "gu",
 "Haitian; Haitian Creole": "ht",
 "Hausa": "ha",
 "Hebrew (modern)": "he",
 "Herero": "hz",
 "Hindi": "hi",
 "Hiri Motu": "ho",
 "Hungarian": "hu",
 "Interlingua": "ia",
 "Indonesian": "id",
 "Interlingue": "ie",
 "Irish": "ga",
 "Igbo": "ig",
 "Inupiaq": "ik",
 "Ido": "io",
 "Icelandic": "is",
 "Italian": "it",
 "Inuktitut": "iu",
 "Japanese": "ja",
 "Javanese": "jv",
 "Kalaallisut, Greenlandic": "kl",
 "Kannada": "kn",
 "Kanuri": "kr",
 "Kashmiri": "ks",
 "Kazakh": "kk",
 "Khmer": "km",
 "Kikuyu, Gikuyu": "ki",
 "Kinyarwanda": "rw",
 "Kirghiz, Kyrgyz": "ky",
 "Komi": "kv",
 "Kongo": "kg",
 "Korean": "ko",
 "Kurdish": "ku",
 "Kwanyama, Kuanyama": "kj",
 "Latin": "la",
 "Luxembourgish, Letzeburgesch": "lb",
 "Luganda": "lg",
 "Limburgish, Limburgan, Limburger": "li",
 "Lingala": "ln",
 "Lao": "lo",
 "Lithuanian": "lt",
 "Luba-Katanga": "lu",
 "Latvian": "lv",
 "Manx": "gv",
 "Macedonian": "mk",
 "Malagasy": "mg",
 "Malay": "ms",
 "Malayalam": "ml",
 "Maltese": "mt",
 "Māori": "mi",
 "Marathi (Marāṭhī)": "mr",
 "Marshallese": "mh",
 "Mongolian": "mn",
 "Nauru": "na",
 "Navajo, Navaho": "nv",
 "Norwegian Bokmål": "nb",
 "North Ndebele": "nd",
 "Nepali": "ne",
 "Ndonga": "ng",
 "Norwegian Nynorsk": "nn",
 "Norwegian": "no",
 "Nuosu": "ii",
 "South Ndebele": "nr",
 "Occitan": "oc",
 "Ojibwe, Ojibwa": "oj",
 "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic": "cu",
 "Oromo": "om",
 "Oriya": "or",
 "Ossetian, Ossetic": "os",
 "Panjabi, Punjabi": "pa",
 "Pāli": "pi",
 "Persian": "fa",
 "Polish": "pl",
 "Pashto, Pushto": "ps",
 "Portuguese": "pt",
 "Quechua": "qu",
 "Romansh": "rm",
 "Kirundi": "rn",
 "Romanian, Moldavian, Moldovan": "ro",
 "Russian": "ru",
 "Sanskrit (Saṁskṛta)": "sa",
 "Sardinian": "sc",
 "Sindhi": "sd",
 "Northern Sami": "se",
 "Samoan": "sm",
 "Sango": "sg",
 "Serbian": "sr",
 "Scottish Gaelic; Gaelic": "gd",
 "Shona": "sn",
 "Sinhala, Sinhalese": "si",
 "Slovak": "sk",
 "Slovene": "sl",
 "Somali": "so",
 "Southern Sotho": "st",
 "Spanish; Castilian": "es",
 "Sundanese": "su",
 "Swahili": "sw",
 "Swati": "ss",
 "Swedish": "sv",
 "Tamil": "ta",
 "Telugu": "te",
 "Tajik": "tg",
 "Thai": "th",
 "Tigrinya": "ti",
 "Tibetan Standard, Tibetan, Central": "bo",
 "Turkmen": "tk",
 "Tagalog": "tl",
 "Tswana": "tn",
 "Tonga (Tonga Islands)": "to",
 "Turkish": "tr",
 "Tsonga": "ts",
 "Tatar": "tt",
 "Twi": "tw",
 "Tahitian": "ty",
 "Uighur, Uyghur": "ug",
 "Ukrainian": "uk",
 "Urdu": "ur",
 "Uzbek": "uz",
 "Venda": "ve",
 "Vietnamese": "vi",
 "Volapük": "vo",
 "Walloon": "wa",
 "Welsh": "cy",
 "Wolof": "wo",
 "Western Frisian": "fy",
 "Xhosa": "xh",
 "Yiddish": "yi",
 "Yoruba": "yo",
 "Zhuang, Chuang": "za"}'''
js = json.dumps(langs)

In [22]:
# translate
model = EasyNMT('opus-mt')
@app.get('/translate', response_class=HTMLResponse)
def translator(lang:str=''):
  prev_lang = 'en'
  if lang:
    for index in range(len(df)):
      try:
        df['Job Title'][index] = model.translate(df[index]['Job Title'], target_lang = lang, source_lang = prev_lang)
        df['Job Description'][index] = model.translate(df[index]['Job Description'], target_lang = lang, source_lang = prev_lang)
        if index != len(df) - 1:
          all_translated = f"""<html>
                            <h2><u>{index} / {len(df)} Jobs translated<br> Try to choose other language maybe.</u></h2>
                            <p>
                            {js}
                            </p>
                  </html>"""
          return all_translated
        else:
          return Response(df.to_json(orient = 'index'), media_type = 'application/json')
      except:
        error_message = f"""<html>
                            <h2><u>Oops! Something went wrong. <br> Try to choose other language maybe.</u></h2>
                            <p>
                            {js}
                            </p>
                  </html>"""
        return error_message
  else:
    content = f"""<html>
                    <h2><u>List of all countries' languages code</u></h2>
                    <p>
                    {js}
                    </p>
                  </html>
              """ 
    return HTMLResponse(content)

In [ ]:
tunnel = ngrok.connect(8000)
print("PUBLIC URL: ", tunnel.public_url)
nest_asyncio.apply()
uvicorn.run(app, port = 8000)

In [18]:
!pkill ngrok